language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check restaurant
  - flake8 restaurant
  - coverage run --source=restaurant manage.py test

after_script:
  - coveralls